# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaysData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TickerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=10)),
                ('opening_price', models.FloatField()),
                ('intrinsic_value', models.FloatField()),
                ('fcfy', models.FloatField()),
                ('pe_ratio', models.FloatField()),
                ('peg_ratio', models.FloatField()),
                ('market_cap', models.FloatField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yfinancial.DaysData')),
            ],
        ),
    ]
